CREATE TABLE "public"."gradebook_column_groups"(
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "class_id" bigint NOT NULL,
    "gradebook_id" bigint NOT NULL,
    "name" text NOT NULL,
    "sort_order" integer
);

ALTER TABLE "public"."gradebook_column_groups"
    ADD CONSTRAINT "gradebook_column_groups_pkey" PRIMARY KEY ("id");

ALTER TABLE "public"."gradebook_column_groups" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."gradebook_column_groups"
    ADD CONSTRAINT "gradebook_column_groups_class_id_fkey" FOREIGN KEY (class_id) REFERENCES classes(id) NOT valid;

ALTER TABLE "public"."gradebook_column_groups" validate CONSTRAINT "gradebook_column_groups_class_id_fkey";

ALTER TABLE "public"."gradebook_column_groups"
    ADD CONSTRAINT "gradebook_column_groups_gradebook_id_fkey" FOREIGN KEY (gradebook_id) REFERENCES gradebooks(id) NOT valid;

ALTER TABLE "public"."gradebook_column_groups" validate CONSTRAINT "gradebook_column_groups_gradebook_id_fkey";

CREATE POLICY "instructors CRUD" ON "public"."gradebook_column_groups" AS permissive
    FOR ALL TO public
    USING (authorizeforclassinstructor(class_id));

CREATE POLICY "everyone in class can view" ON "public"."gradebook_column_groups" AS permissive
    FOR SELECT TO public
    USING (authorizeforclass(class_id));

-- Adding Gradebook Column Group Id
ALTER TABLE "public"."gradebook_columns"
    ADD COLUMN "gradebook_column_groups_id" bigint;

-- Gradebook columns should have reference to the column groups
ALTER TABLE "public"."gradebook_columns"
    ADD CONSTRAINT "gradebook_columns_gradebook_column_groups_id_fkey" FOREIGN KEY (gradebook_column_groups_id) REFERENCES gradebook_column_groups(id) NOT valid;

ALTER TABLE "public"."gradebook_columns" validate CONSTRAINT "gradebook_columns_gradebook_column_groups_id_fkey";

DO $$
DECLARE
    eachrow record;
    applied_gradebook_id integer;
    slug_part text[];
    -- Applied means we are using it, current means it's a temp variable
    applied_slug_prefix text;
    current_slug_prefix text;
    applied_sort_order integer;
    applied_group_id integer;
    applied_name text;
    group_sort_order integer := 0;
BEGIN
    FOR eachrow IN
    SELECT
        id,
        class_id,
        gradebook_id,
        slug,
        sort_order
    FROM
        gradebook_columns
    ORDER BY
        gradebook_id,
        sort_order LOOP
            slug_part := string_to_array(eachrow.slug, '-');
            IF array_length(slug_part, 1) >= 3 AND slug_part[1] = 'assignment' THEN
                current_slug_prefix := slug_part[1] || '-' || slug_part[2];
            ELSE
                current_slug_prefix := slug_part[1];
            END IF;
            IF applied_slug_prefix IS NULL OR applied_slug_prefix <> current_slug_prefix OR eachrow.sort_order <> applied_sort_order + 1 OR applied_gradebook_id IS DISTINCT FROM eachrow.gradebook_id THEN
                IF applied_gradebook_id IS DISTINCT FROM eachrow.gradebook_id THEN
                    group_sort_order := 0;
                END IF;
                group_sort_order := group_sort_order + 1;
                IF slug_part[1] = 'assignment' THEN
                    applied_name := initcap(slug_part[2]);
                ELSIF slug_part[1] <> 'assignment'
                        AND array_length(slug_part, 1) = 2
                        AND slug_part[2] ~ '^\d+$' THEN
                        applied_name := initcap(slug_part[1]);
                ELSE
                    applied_name := initcap(slug_part[1]);
                END IF;
                applied_slug_prefix := current_slug_prefix;
                applied_gradebook_id := eachrow.gradebook_id;
                INSERT INTO gradebook_column_groups(class_id, gradebook_id, name, sort_order)
                    VALUES (eachrow.class_id, eachrow.gradebook_id, applied_name, group_sort_order)
                RETURNING
                    id
                INTO
                    applied_group_id;
            END IF;
            applied_sort_order := eachrow.sort_order;
            UPDATE
                gradebook_columns
            SET
                gradebook_column_groups_id = applied_group_id
            WHERE
                id = eachrow.id;
        END LOOP;
END
$$;

-- ALTER TABLE "public"."gradebook_columns"
--     ALTER COLUMN "gradebook_column_groups_id";
